
services:
  mongo:
    image: mongo:7
    restart: always
    env_file:
      - .env
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  bot:
    build: .
    depends_on:
      - mongo
    env_file:
      - .env

volumes:
  mongo-data:
