version: '3.8'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  bot:
    build: .
    depends_on:
      - mongo
    env_file:
      - .env

volumes:
  mongo-data:
